var express=require('express')
var app=express()
var path=require('path')
console.log(__dirname)
var publicpath=path.resolve(__dirname,'001.txt')
console.log(publicpath)
app.use(express.static(publicpath))
app.listen(3000)